version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoints/app-entrypoint.sh
    # image: ufcvirtualdevops2022/solar:v1
    depends_on:
      - database
      - redis-db
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    networks:
      solar_net:
        ipv4_address: 172.20.0.10
    env_file: .env

  database:
    image: postgres:14
    networks:
      solar_net:
        ipv4_address: 172.20.0.11
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: "solar"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    # ports:
    #   - "5432:5432"

  redis-db:
    image: redis:7.0.4
    networks:
      solar_net:
        ipv4_address: 172.20.0.12
    volumes:
      - db_redis:/data
    # ports:
    #   - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    networks:
      solar_net:
        ipv4_address: 172.20.0.13
    # ports:
    #     - "1025:1025"
    #     - "8025:8025"

volumes:
  gem_cache:
  db_data:
  db_redis:
  node_modules:

networks:
  solar_net:
    ipam:
      config:
        - subnet: 172.20.0.0/16