
production:
  websocket:
    host: '127.0.0.1'
    port: 3002
  import_users:
    media_path: "/media/admin/logs/users/import"
    header: "Nome;CPF;Sexo;Email;Endereço;País;Estado;Cidade;Instituição"
  url_options:
    :host: "localhost"
    :port: 3000

development:
  websocket:
    host: '127.0.0.1'
    port: 3002
  import_users:
    media_path: "/media/admin/logs/users/import"
    header: "Nome;CPF;Sexo;Email;Endereço;País;Estado;Cidade;Instituição"
  url_options:
    :host: "localhost"
    :port: 3000

test:
  websocket:
    host: '127.0.0.1'
    port: 3002
  import_users:
    media_path: "/media/admin/logs/users/import"
    header: "Nome;CPF;Sexo;Email;Endereço;País;Estado;Cidade;Instituição"
  url_options:
    :host: "localhost"
    :port: 3000
