
common: &common
dns: <%= ENV['DNS'] %>
websocket:
  port: <%= ENV['WEBSOCKET_PORT'] %>
  host: <%= ENV['WEBSOCKET_HOST'] %>
import_users:
  media_path: "/media/admin/logs/users/import"
  header: "Nome;CPF;Gênero;Email;Endereço;País;Estado;Cidade;Instituição;Cpf;Turma"

production:
  <<: *common
  devise:
    secret_key_base: ""
  url_options:
    :host: <%= ENV['HOST'] %>
    :port: 80
  domain: "virtual.ufc.br"

development:
  <<: *common
  devise:
    secret_key_base: ""
  url_options:
    :host: "localhost"
    :port: 3000

test:
  <<: *common
