smtp_settings:
  :address: 
  :authentication: 
  :domain: 
  :user_name: 
  :password: 
  :enable_starttls_auto: true
  :port: 25

default_sender:
  :from: 

default_url_options:
  :host: <%= ENV['HOST'] %>

mass_emails:
  scheduled_time: 30
  max_amount: 300