# Schema search path. The server defaults to $user,public
#schema_search_path: myapp,sharedapp,public

# Minimum log levels, in increasing order:
#   debug5, debug4, debug3, debug2, debug1,
#   log, notice, warning, error, fatal, and panic
# The server defaults to notice.
#min_messages: warning

common: &common
  encoding: UTF8
  adapter: postgresql
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>

development:
  <<: *common
  database: <%= ENV["DB_NAME"] %>

test:
  <<: *common
  database: solar_test

production:
  <<: *common
  database: <%= ENV["DB_NAME"] %>