## mail settings

smtp_settings:
  :address: 'smtp.gmail.com'
  :authentication: 'plain'
  :domain: 'virtual.ufc.br'
  :user_name: 'teste@virtual.ufc.br'
  :password: 's0lartest'
  :enable_starttls_auto: true
  :port: 587

default_sender:
  :from: 'teste@virtual.ufc.br'

default_url_options:
  :host: 'apolo11.virtual.ufc.br'