common: &common
  key: "po09lk87mn65qw23as45bgty"
  IV: "12qw34er"
  params: "userId=user_id;profilesIds=profiles_ids;savsIds=savs_ids"

development:
  <<: *common
  url: "url"

production:
  <<: *common
  url: "url"