#language: pt

Funcionalidade: Cadastrar usuário
  Como um novo usuário do solar
  Eu quero me cadastrar
  Para acessar os recursos do sistema

Cenário: Acessar página de cadastro de novo usuário
  Dado que eu nao estou cadastrado
    E que estou em "Login"
    E eu clico no link "Cadastrar"
    E que eu preenchi "cpf" com "724.164.753-04"
  Quando eu clicar em "Verificar"
  Então eu deverei ver "Nome"
    E eu deverei ver "CPF"
    E eu deverei ver "Data de Nascimento"
    E eu deverei ver "Sexo"
    E eu deverei ver "Necessidades especiais"
    E eu deverei ver o link "Próximo"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Apelido"
    E eu deverei ver "Login"
    E eu deverei ver "Senha"
    E eu deverei ver "Confirmação da senha"
    E eu deverei ver "E-mail"
    E eu deverei ver "Confirmação do e-mail"
    E eu deverei ver "E-mail alternativo"
    E eu deverei ver o link "Anterior"
    E eu deverei ver o link "Próximo"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Endereço"
    E eu deverei ver "Número"
    E eu deverei ver "Complemento"
    E eu deverei ver "Bairro"
    E eu deverei ver "CEP"
    E eu deverei ver "País"
    E eu deverei ver "Estado"
    E eu deverei ver "Cidade"
    E eu deverei ver "Telefone"
    E eu deverei ver "Celular"
    E eu deverei ver o link "Anterior"
    E eu deverei ver o link "Próximo"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Instituição"
    E eu deverei ver o link "Próximo"
    E eu deverei ver o botao "Concluir"

@javascript
Cenário: Cadastrar novo usuário
  Dado que estou em "Cadastrar usuario"
    E que eu preenchi "Nome" com "Usuário do Solar"
    E que eu preenchi "CPF" com "724.164.753-04"
    E que eu selecionei a data "13/12/2001" no campo com id "user_birthdate"
    E que eu selecionei "Sexo" com "Masculino"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Apelido"
    E que eu preenchi "Apelido" com "usuario"
    E que eu preenchi "Login" com "usuario"
    E que eu preenchi "Senha" com "123456"
    E que eu preenchi "Confirmação da senha" com "123456"
    E que eu preenchi "user_email" com "usuario@solar.virtual.ufc.br"
    E que eu preenchi "user_email_confirmation" com "usuario@solar.virtual.ufc.br"
    E que eu preenchi "user_alternate_email" com "usuario-alternativo@solar.virtual.ufc.br"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Endereço"
    E que eu preenchi "Endereço" com "Rua Sei Não"
    E que eu preenchi "Número" com "123"
    E que eu preenchi "Complemento" com "Ap 000"
    E que eu preenchi "Bairro" com "Sei lá qual"
    E que eu preenchi "CEP" com "60000-000"
    E que eu preenchi "País" com "Brasil"
    E que eu selecionei "Estado" com "CE"
    E que eu preenchi "Cidade" com "Fortaleza"
    E que eu preenchi "Telefone" com "8533222233"
    E que eu preenchi "Celular" com "8588888888"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Instituição"
    E que eu preenchi "Instituição" com "UFC"
  Quando eu clicar em "Concluir"
  Então eu deverei visualizar "Sair"
    E eu deverei visualizar "Home"

Cenário: Cadastrar novo usuário com dados inválidos
  Dado que estou em "Cadastrar usuario"
    E que eu preenchi "Nome" com "a"
    E que eu preenchi "CPF" com "724.164.753-04"
    E que eu selecionei a data "13/12/2001" no campo com id "user_birthdate"
    E que eu selecionei "Sexo" com "Masculino"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Apelido"
    E que eu preenchi "Apelido" com "usuario"
    E que eu preenchi "Login" com "usuario"
    E que eu preenchi "Senha" com "123456"
    E que eu preenchi "Confirmação da senha" com "123456"
    E que eu preenchi "user_email" com "usuario@solar.virtual.ufc.br"
    E que eu preenchi "user_email_confirmation" com "usuario@solar.virtual.ufc.br"
    E que eu preenchi "user_alternate_email" com "usuario-alternativo@solar.virtual.ufc.br"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Endereço"
    E que eu preenchi "Endereço" com "Rua Sei Não"
    E que eu preenchi "Número" com "123"
    E que eu preenchi "Complemento" com "Ap 000"
    E que eu preenchi "Bairro" com "Sei lá qual"
    E que eu preenchi "CEP" com "60000-000"
    E que eu preenchi "País" com "Brasil"
    E que eu selecionei "Estado" com "CE"
    E que eu preenchi "Cidade" com "Fortaleza"
    E que eu preenchi "Telefone" com "8533222233"
    E que eu preenchi "Celular" com "8588888888"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Instituição"
    E que eu preenchi "Instituição" com "UFC"
  Quando eu clicar em "Concluir"
    Então eu deverei ver "é muito curto(a) (mínimo: 6 caracteres)"

@javascript
Cenário: Cadastrar novo usuário e sair logo em seguida
  Dado que estou em "Cadastrar usuario"
    E que eu preenchi "Nome" com "Usuário do Solar"
    E que eu preenchi "CPF" com "724.164.753-04"
    E que eu selecionei a data "13/12/2001" no campo com id "user_birthdate"
    E que eu selecionei "Sexo" com "Masculino"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Apelido"
    E que eu preenchi "Apelido" com "usuario"
    E que eu preenchi "Login" com "usuario"
    E que eu preenchi "Senha" com "123456"
    E que eu preenchi "Confirmação da senha" com "123456"
    E que eu preenchi "user_email" com "usuario@solar.virtual.ufc.br"
    E que eu preenchi "user_email_confirmation" com "usuario@solar.virtual.ufc.br"
    E que eu preenchi "user_alternate_email" com "usuario-alternativo@solar.virtual.ufc.br"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Endereço"
    E que eu preenchi "Endereço" com "Rua Sei Não"
    E que eu preenchi "Número" com "123"
    E que eu preenchi "Complemento" com "Ap 000"
    E que eu preenchi "Bairro" com "Sei lá qual"
    E que eu preenchi "CEP" com "60000-000"
    E que eu preenchi "País" com "Brasil"
    E que eu selecionei "Estado" com "CE"
    E que eu preenchi "Cidade" com "Fortaleza"
    E que eu preenchi "Telefone" com "8533222233"
    E que eu preenchi "Celular" com "8588888888"
  Quando eu clicar no link "Próximo"
  Então eu deverei ver "Instituição"
    E que eu preenchi "Instituição" com "UFC"
  Quando eu clicar em "Concluir"
  Então eu deverei visualizar "Sair"
    E eu deverei visualizar "Home"
  Quando eu clicar no link de conteudo "Sair"
  Então eu deverei visualizar "Login"
    E eu deverei visualizar "Cadastrar"
